### ISSUE TITLE
It alwys return "Unauthorized"?

### ISSUE THREAD

**Issue by emjimadhu** [antonybudianto/express-firebase-middleware#4]
Hello there, first of all thank you so much for this great middleware.

I followed your guide. but i always get `Unauthorized`, why?

i am using postman to check. i send request with this header `'Authorization': 'Bearer ASDKFJHASDKFJH5`

but still got the same error.

**Comment by antonybudianto** [comment]
Hi, may I know how do you get the token? If it's a [custom token](https://firebase.google.com/docs/auth/admin/create-custom-tokens), it won't work unfortunately.

Also it'll be helpful if you can provide some error logs

**Comment by emjimadhu** [comment]
First what is cliet id you are referring? its `UID`? if so can you explain how this works?

**Comment by antonybudianto** [comment]
Not UID, It's the **token** when user already logged-in using Firebase, you can obtain them using their SDK (Web, Android, or iOS)

For instance:
https://stackoverflow.com/questions/38004233/how-to-get-accesstoken-for-firebase-3-using-javascript

The way it works is when you send that token, I validate it using their Firebase Admin SDK, if it's valid then return the user object, if not, then 401 

For more information:
https://firebase.google.com/docs/auth/admin/verify-id-tokens

**Comment by emjimadhu** [comment]
@antonybudianto hey thank you soo much.. for `signInWithEmailAndPassword` `getIdToken()` works perfectly.

but for social login it is not working. i used `accessToken` from `credential` object and i used `idToken` from credential object. it responed with `unauthorized`.

**Comment by antonybudianto** [comment]
how about:
```
firebase.auth().currentUser.getToken(/* forceRefresh */ true).then(function(idToken) {
  // Send token to your backend via HTTPS
  // ...
}).catch(function(error) {
  // Handle error
});
```

**Comment by brightlylit** [comment]
I'm getting exactly the same problem. Have tried above fix too, no joy.

**Comment by nanborklabs** [comment]
Hey @emjimadhu  this is unbelievable, ran into the same. @antonybudianto  thanks for your solution. It is working now.
