### ISSUE TITLE
On the 3rd step, where to put the authorization token

### ISSUE THREAD

**Issue by aaravkr** [antonybudianto/express-firebase-middleware#6]
The 3rd step is unclear. it would be great if you can elaborate it a bit.

**Comment by antonybudianto** [comment]
You don't need to save/put the token manually, it's from the Firebase SDK, it's on readme
https://firebase.google.com/docs/auth/admin/verify-id-tokens

**Comment by antonybudianto** [comment]
or perhaps you mean this one?
```
Authorization: Bearer <your-client-token>
```

It's the request header, you can set it using your HTTP client like fetch or axios.
